// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQLgjz8kWZGoKnvalH3evEnfH5pKSuSV8',
    appId: '1:58648859952:web:4338b958872add0ccf64f5',
    messagingSenderId: '58648859952',
    projectId: 'fbla-aspire',
    authDomain: 'fbla-aspire.firebaseapp.com',
    storageBucket: 'fbla-aspire.firebasestorage.app',
    measurementId: 'G-S17NCGPX8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsoqUrNerj2w5IGoAGTV_TtNiq4hpRFYs',
    appId: '1:58648859952:android:2ae4e4ac4dada2b3cf64f5',
    messagingSenderId: '58648859952',
    projectId: 'fbla-aspire',
    storageBucket: 'fbla-aspire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiiwMk120WxiVtTmXLuuqsQc0MwJ4tU0c',
    appId: '1:58648859952:ios:28b16c7d58ed7c05cf64f5',
    messagingSenderId: '58648859952',
    projectId: 'fbla-aspire',
    storageBucket: 'fbla-aspire.firebasestorage.app',
    iosBundleId: 'com.example.fblaConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiiwMk120WxiVtTmXLuuqsQc0MwJ4tU0c',
    appId: '1:58648859952:ios:28b16c7d58ed7c05cf64f5',
    messagingSenderId: '58648859952',
    projectId: 'fbla-aspire',
    storageBucket: 'fbla-aspire.firebasestorage.app',
    iosBundleId: 'com.example.fblaConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQLgjz8kWZGoKnvalH3evEnfH5pKSuSV8',
    appId: '1:58648859952:web:c0e92293e8bfb67acf64f5',
    messagingSenderId: '58648859952',
    projectId: 'fbla-aspire',
    authDomain: 'fbla-aspire.firebaseapp.com',
    storageBucket: 'fbla-aspire.firebasestorage.app',
    measurementId: 'G-2TVLC2C7CZ',
  );
}
